apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    kiamol: ch08-lab
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.17-alpine
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx/
  volumeClaimTemplates:
    - metadata:
        name: logs
        labels:
          kiamol: ch08-lab
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi