apiVersion: v1
kind: Service
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  ports:
    - port: 8070    
      targetPort: 80
      name: http
    - port: 8080
      targetPort: 8080
      name: version
  selector:
    app: pi-web
  type: LoadBalancer