apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      initContainers:
        - name: init-script
          image: kiamol/ch05-pi
          command: [ 'sh', '-c', "echo '#!/bin/sh\ndotnet Pi.Web.dll -m Web' > /init-out/startup.sh  && chmod a+x /init-out/startup.sh" ]
          volumeMounts:
            - name: scripts-dir
              mountPath: /init-out
        - name: init-html
          image: kiamol/ch05-pi
          command: ['sh', '-c', "echo '<!DOCTYPE html><html><body><h1>v2</h1></body></html>' > /versions/index.html"]
          volumeMounts:
            - mountPath: /versions
              name: version-dir
      containers:
        - image: kiamol/ch05-pi
          command: ["/scripts/startup.sh"]
          name: web
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: scripts-dir
              mountPath: /scripts
        - image: kiamol/ch05-pi
          command: ['sh', '-c', 'while true; do echo -e "HTTP/1.1 200 OK\nContent-Type: text/html\nContent-Length: 62\n\n$(cat /versions/index.html)" | nc -l -p 8080; done']
          name: web-version
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: version-dir
              mountPath: /versions
      volumes:
        - name: scripts-dir
          emptyDir: {}
        - name: version-dir
          emptyDir: {}
