apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["/scripts/startup.sh"]
          name: web
          ports:
            - containerPort: 80
              name: http

# Command inside the container is: dotnet Pi.Web.dll
# Also has some options:
#  /app # dotnet Pi.Web.dll -m
#  Usage - Pi.Web -options
#
#  GlobalOption          Description
#  Mode (-m)             Run mode [Default='console']
#  Web
#  Console
#  File
#  DecimalPlaces (-dp)   Decimal places to calculate [Default='20']
#  OutputPath (-o)       Output path for file mode [Default='/pi.txt']
